name: Process Markdown Files

on:
  push:
    branches:
      - main  
    paths:
      - '**/*.md'  

jobs:
  process-markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  
    - name: Run Script
      run: python converter.py  
      working-directory: .  
