name: Process Markdown Files

on:
  push:
    branches:
      - main
    paths:
      - '**/*.md'

jobs:
  process-markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run Script
      run: python convert_latex.py

    - name: Commit and Push Changes
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add -A
        git commit -m "Update Markdown files via GitHub Actions" || echo "No changes to commit"
        git push

    - name: List modified files
      run: git status
